### ISSUE TITLE
Discussion: move class files to sub package datamodel 

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#10]
Currently all classes of the data model are located @ `edu.ie3`. In previous versions we had all data model related stuff located @`edu.ie3.datamodel`. Is there any specific reason that we  don't do this anymore? 
Otherwise I would suggest the following:
- move everything into sub-package `edu.ie3.datamodel`
- move  `ValidationTools` ->  `edu.ie3.datamodel.utils` and rename it to `ValidationUtils`
- move `InvalidEntityException`and `UnsafeEntityException` into new to create `edu.ie3.datamodel.exceptions`
- delete `edu.ie3.datamodel.validation`

**Comment by mia-krause** [comment]
There is no specific reason, other than edu.ie3.datamodel.models sounded a bit redundant. But from a package supply view it probably makes sense.

**Comment by ckittl** [comment]
See PR #58 for instructions on how to make integration easier.
