### ISSUE TITLE
Adapt sonarqube.gradle

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#132]
As far as I can relate, the content of `sonarqube.gradle`

1. is not used at all and
2. outdated / wrong.

Would you be so kind and check, if the file can be deleted and if it would be worthwhile to take over some of the arguments into the `Jenkinsfile`?

**Comment by ckittl** [comment]
Additionally, while working on #130, I got to know, that Sonarqube is scanning doc files as well. Maybe we can figure out a way, that only the really necessary files are scanned.

**Comment by johanneshiry** [comment]
build.gradle is missing `apply from: scriptsLocation + 'sonarqube.gradle'`

**Comment by ckittl** [comment]
> Additionally, while working on #130, I got to know, that Sonarqube is scanning doc files as well. Maybe we can figure out a way, that only the really necessary files are scanned.

Seems, that I was wrong. Also with the exclusion of docs folder, the error seems to pop up from time to time.
