### ISSUE TITLE
Make constructor of GridAndGeoUtils protected

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#135]
... to allow for extending this class.

**Comment by johanneshiry** [comment]
Can you provide a little bit more insights why this is necessary/what's the reason for this? I would assume that we need this somewhere if it is marked as a bug?

**Comment by ckittl** [comment]
Applies for all utility classes, that have a private constructor. Therefore, extending those utility classes in the projects, using those.

**Comment by ckittl** [comment]
As of discussion, we intend not to extend utility classes but use them directly.
