### ISSUE TITLE
Add copy builder implementations for thermal instances

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#165]
Currently, copy implementations are not implemented for the following `AssetInput` entities and hence throw a `NotImplementedException`. It should be considered implementing the corresponding methods for these entities soon.

- CylindricalStorageInput
- ThermalBusInput
- ThermalHouseInput

**Comment by ahamshubham** [comment]
I believe I need to add a builder implementation for `CylindricalStorageInput`, `ThermalBusInput` and `ThermalHouseInput` similar to how it is done in `SystemParticipantInput` using `SystemParticipantInputCopyBuilder`.
