### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by mia-krause** [ie3-institute/PowerSystemDataModel#170]
I found two broken links.

1. If I click on a SonarQube check under a PR, I there have the option to click "View in SonarQube". This however doesn't work as the linked address is on localhost.
2. If I want to open the API docs linked in the readme (https://ie3-institute.github.io/PowerSystemDataModel/javadoc/), I get a 404.

**Comment by ckittl** [comment]
Part 2 of your issue is resolved. GitHub pages accidentally deactivated itself, so no deployment took place.

For part 1, as far as I can remember the discussion with @johanneshiry the broken link issue comes from SonarQube announcements themselves and is therefore out of our reach.
