### ISSUE TITLE
Rename all time based columns to "time"

### ISSUE THREAD

**Issue by mia-krause** [ie3-institute/PowerSystemDataModel#175]
This should be done for three reasons:

1. They represent a time, so they should be named as such
2. It's more intuitive if all columns on all models representing the same field, have the same value
3. InfluxDB requires the time based field to be named "time"

However, as this is a huge change in the existing data, this change should be paused until the next release.

**Comment by johanneshiry** [comment]
Would you mind giving a little bit more context and which models are affected? As we sometimes use several different time fields I'm not sure if this will work.

**Comment by mia-krause** [comment]
It affects two kinds of models: TimeBasedValues and ResultEntities. While the timestamp in TBVs is already called "time" it is called "timestamp" for results. They only other timestamps I can think of belong to OperationTime, but that class has two timestamps, so they can't be named that way.

**Comment by ckittl** [comment]
@mia-krause Please check, if this issue could be added to #149 to avoid duplicates of similar issues.
