### ISSUE TITLE
Implement mapping between participant models and time series

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#203]
Currently, there is no possibility to map time series to grid participants. As of discussion with @johanneshiry and @sensarmad we will go for an explicit mapping between participants' and time series' uuids. Therefore, several adaptions need to be made:

- [x] Adapt file naming for time series
  - Individual time series: `its_<uuid_of_time_series>`
  - Repetitive time series: `rts_<uuid_of_time_series>`
- [x] Enhance naming strategy with routine to extract the meta information (time series type and uuid) from name
- [x] Establish distinct mapping file `participant_to_time_series.csv`
  - [ ] Implement writing routine
  - [ ] Implement reading routine
  - [ ] Implement routines for validation and filtering time series and participants

**Comment by johanneshiry** [comment]
Looking forward to this feature as I think this will definitely push the usability of the PDSM again. 
A few remarks that came to my mind when reading the task description:

- Does it make sense to also include time series in `SubGridContainer` and `JointGridContainer`? 
- I might provide support for the mapping reading and writing routine. Let me know if you want to discuss this further or if I can provide support here.

**Comment by ckittl** [comment]
I'm not sure about the first point, yet. But I will think further about it. 😃 Thanks for your offer, I will come back to this!

**Comment by ckittl** [comment]
I would like to hand over this task to you, @mia-krause.

As you see in the initial description of this issue, some tasks are already accomplished in in the linked pull request. It would be great, if you could take over the part of defining the structure of the mapping file. As of earlier discussion, we would like to have a file, that maps from participant UUID to time series UUID (having a n:1 mapping, which should be easier to handle). We do not need any null handling or default definitions. When there is no time series assigned to one participant, there simply is no entry in the table.

From my point of view the rest of the task involves additonally:

- [ ] Definition of meaningful column headers
- [ ] Definition and implementation of a concept, that is similar to time series (having a grouping class, that in this application case offers some mapping capability)
- [ ] Include this new structure in `FileNamingStrategy`, `DefaultInputHierarchy` and  thereby in `HierarchicNamingStrategy`
- [ ] Write tests for this case

and of course, writing and reading routines as mentioned above.

**Comment by johanneshiry** [comment]
Maybe also connected with this issue? - https://github.com/ie3-institute/PowerSystemDataModel/issues/172

**Comment by ckittl** [comment]
Implicitly covered in the adaptions and thanks for detecting the duplicate.
