### ISSUE TITLE
Release PowerSystemUtils 1.5.1 and adapt build.gradle

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#211]
Before releasing version 2.0 of psdm I would love to have a new minor version release of PowerSystemUtils, so that the stable version of psdm refers to a stable version of PowerSystemUtils.

**Comment by johanneshiry** [comment]
Not possible anymore, as we've already introduced breaking changes. However, there is some compatibility between the stable PSDM/Utils versions before the indriya introduction.
