### ISSUE TITLE
Add Weather Sources

### ISSUE THREAD

**Issue by mia-krause** [ie3-institute/PowerSystemDataModel#223]

**Comment by johanneshiry** [comment]
@mia-krause would you mind providing a more meaningful issue description please? :)

**Comment by ckittl** [comment]
@mia-krause As soon as #219 is merged, you can build upon the `CsvTimeSeriesSource` to implement a `CsvWeatherSource`, as the time series source yet is capable of reading in weather time series (one might have to implement a `CsvIdCoordinateSource`).
