### ISSUE TITLE
Remove usage of deprecated time tools

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#225]
Replace all usages of `edu.ie3.util.TimeTools` by `edu.ie3.util.TimeUtil`.

Please try to accomplish this task as one of the last tasks before releasing version 2.0 to avoid uncovered places by closing other PRs.

**Comment by EikeSan** [comment]
Hello @ckittl, I created a new PR to this. Please check #226.

**Comment by ckittl** [comment]
Closed via #288
