### ISSUE TITLE
Fix typo in README.md

### ISSUE THREAD

**Issue by faeb5** [ie3-institute/PowerSystemDataModel#254]
There is small a typo in README.md inside the section _Supported physical models_" It says _swithces_ instead of _switches_.

I would like to fix this typo.

**Comment by johanneshiry** [comment]
Hi @faeb5 
thanks for your hint. 
We use a modified git flow branch model to add new features or fix bugs. Please fork the repo first, then open a new branch following the naming conventions in our [contributing guidelines](https://github.com/ie3-institute/PowerSystemDataModel/blob/dev/CONTRIBUTING.md#contributing-code] and hand in a pull request for the new branch in your fork accordingly. 

If you have any questions on the procedure please let me know. 

Thanks in advance for your contribution.
