### ISSUE TITLE
Fix PsdmTimeBasedWeatherValueFactory

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#267]
The column names of the `PsdmTimeBasedWeatherValueFactory` are currently invalid.

- time -> time 
- coordinate -> **coordinateid**
- diffuseirradiation -> **diffuseirradiance**
- directirradiation -> **directirradiance**
- winddirection -> winddirection
- windvelocity -> windvelocity
- temperature -> temperature

Furthermore the `datum` column of the`IconTimeBasedWeatherValueFactory` might be renamed to `time` as well. (considering #175)

Furthermore, `Psdm` should be renamed to `Cosmo`.

**Comment by ckittl** [comment]
As of discussion today: The factory does not reflect the _actual_ scheme in the weather database. Therefore, either the factory has to be altered or at the same time the scheme of the data base.

An argument for changing the data scheme is, that InfluxDB requires the time information to be called `time`. On the other hand, not changing the scheme, would not lead to breaking other applications.

Decision:
- [ ] Alter the scheme for the COSMO model within the data base, as this kind of is legacy data as well.
- [ ] Rename `PsdmTimeBaseWeatherValueFactory` to `CosmoTimeBasedWeatherValueFactory`
- [ ] Alter the scheme of ICON weather data as well (`datum` -> `time`, `coordinate` -> `coordinateid`) -- change the column name here as well

**Comment by ckittl** [comment]
Even more issues than expected...

- [ ] `CouchbaseWeatherSource` takes name of coordinate column from constructor, `InfluxDbWeatherSource` from `TimeBasedWeatherValueFactory`-implementation for queries -> Resolve this inhomogeneity
- [ ] Field names in Couchbase (the actual source) are plain and not snake case as in other sources -> can it be harmonized?

**Comment by ckittl** [comment]
Breaking down the above discussion to actual tasks:

- [x] Adaption of COSMO column scheme in code
  - targeted in: #321 
- [ ] Adapt COMSO column scheme in all existing sources (files, database, ...)
- [x] Adapt ICON column scheme in code
  - targeted in: #329
- [ ] Adapt ICON column scheme in all existing sources (files, database, ...)
- [ ] `SqlWeatherSource` determines column name by querying the meta scheme
  - [ ] Check where this is actually used
  - [ ] Try to get rid of that implementation and use fixed column name convention instead
- [ ] Change Couchbase column names from flat to snake case
- [ ] Reflect the changes from here in `DWDWeatherTools` aka. check and create issues there
