### ISSUE TITLE
Convenience Constructor for TimeSeriesContainer

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#273]
... that allows handing over a bunch of time series and takes over the sorting according to type by itself.

**Comment by sebastian-peter** [comment]
`TimeSeriesContainer` was removed [here](https://github.com/ie3-institute/PowerSystemDataModel/commit/4a63b1d74423c349042386be72793f3e7fdce6ef) which renders this obsolete I guess. Reopen if I'm wrong here
