### ISSUE TITLE
(Don't) consider a switch to java 11 (yet)

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#307]
As java 1.8 becomes more and more outdated and our dependencies start switching to java 11 (new LTS) we might consider switching to java 11 as well in the future. This issue is to track which dependencies cannot be updated anymore because they are compiled with java 11 already. When we reached a critical mass, we should start a switch from java 8 to java 11.

Dependencies currently compiled and provided using java 11:
- jGraphT

**Comment by sebastian-peter** [comment]
We're at JDK 17 now. jgrapht is still to be updated
