### ISSUE TITLE
Move function totalLengthOfLineString() from PSDM GridAndGeoUtils to PowerSystemUtils GeoUtils

### ISSUE THREAD

**Issue by NGL04** [ie3-institute/PowerSystemDataModel#310]
Move function `totalLengthOfLineString()` (+test) from PSDM `src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java` to `GeoUtils` in PowerSystemUtils
-> remove in PSDM

referring issue in PowerSystemUtils: https://github.com/ie3-institute/PowerSystemUtils/issues/76

**Comment by ckittl** [comment]
Content of this issue has been merged into #316
