### ISSUE TITLE
The checkNode function in ValidationUtils doesn't seem to check for existing subnet

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemDataModel#334]
The checkNode method in `models.utils.ValidationUtils` is documented to check if the subnet of the node is not null but doesn't seem to fulfill its promise.

![image](https://user-images.githubusercontent.com/63147366/115253006-44cf4780-a12c-11eb-9ddb-9c0ca4bac2af.png)

**Comment by Utkarsha-dev05** [comment]
The changes needed to resolve this issue are already addressed in checkMethod in **models.utils.ValidationUtils**.
