### ISSUE TITLE
New ChpTypeInput might require new factory

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#39]
I looks like the new changes introduced by @ckittl break the `SystemParticipantTypeInputFactory` in the sense that the factory no longer can produce `ChpTypeInput` entities at it requires not a simple, but a complex factory. 

@sebastian-peter please consult @ckittl or me when you're back in office so that we can talk about this asap or add any suggestions for a solution below.

**Comment by sebastian-peter** [comment]
ThermalStorageInput is now moved to ChpInput, which has to dealt with by a complex entity factory anyways.
