### ISSUE TITLE
Extend Operator with static field NO_OPERATOR

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#40]
Currently an `OperatorInput` is required by all input entities, but it might be the case, that input entities don't have an operator. In that case putting `null` into the `OperatorInput` field in the corresponding input entity would be doable, but not indicating what exactly the `null` stands for (error in entity creation, no operator, ...). Hence, some default fields for the `OperatorInput` might make sense.

**Comment by ckittl** [comment]
Successfully resolved
