### ISSUE TITLE
AggregatedGridInput does not use VoltageLevel but NodeInput does

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#43]
I just discovered, that `AggregatedGridInput` as a `setVoltLvl()`-method that allows setting a string. In contrast, `NodeInput` also contains a field `voltLvl` which is of type `VoltageLevel`. @mia-krause can you explain me why we distinguish between this and why this isn't harmonized? I think this is a little bit confusing or even not correctly implemented?!

**Comment by ckittl** [comment]
As of discussion with @johanneshiry, we decided to introduce a new model for a voltage level and refer to it from `NodeInput`. Therefore, there shouldn't be an equivalent attribute in `AggregatedGridInput`. Instead, we will introduce an aggregation function there to determine the most dominant voltage level in an `AggregatedGridInput`.

**Comment by ckittl** [comment]
Will be addressed with issue #54
