### ISSUE TITLE
Fix snapshot deployment

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/PowerSystemDataModel#500]
Same error is occurring here: https://github.com/ie3-institute/PowerSystemUtils/issues/213

Also, project compilation seems to happen at least twice in total, which might not be necessary.

**Comment by ckittl** [comment]
You might consider adding Thomas and Sebastian to the deployment information?

**Comment by johanneshiry** [comment]
Resolved by credentials update in CI
