### ISSUE TITLE
Create convenience function for parsing grid files and returning `JointGridContainer`

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemDataModel#502]
Currently parsing a grid requires instantiating all the different sources (`RawGridSource`, `SystemParticipantSource`, .. ) and sticking them in a `JointGridContainer`manually. It would be nice to also have a convenience function that takes the folder, the csv delimiter and the naming strategy and returns a `JointGridContainer`.

**Comment by johanneshiry** [comment]
Thanks for the feature request. I'm somehow divided on this. 

On the one hand I understand that there might be a need for such a "SuperSource" combining a specific source combination.
On the other hand, the sources have been designed with flexibility in mind, which means that the idea behind them is to use different sources (e.g. from .csv-files and a database) to read a full grid. This means that if properly configured you could read the grid structure from a database while flexible providing different types from a .csv-file which gives you a huge flexibility in input data handling. 

That said, I'm open to a more restrictive source initialization as **additional** feature. The only request I would have is that 
a) we keep the existing implementations and flexible approach for the sketched use cases 
b) we provide additional "SuperSources" (or however you wanna call them) or similar which only allow **one** source (e.g. .csv-file only or specific db only)
c) we document the behavior of these "SuperSources" properly and directly point to the flexible sources as well

What do you think? Are you willing to provide a draft for a "SuperSource"? As far as I get your post you only want to introduce one for .csv-files?
