### ISSUE TITLE
Return type of load profile

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#613]
https://github.com/ie3-institute/PowerSystemDataModel/blob/74124101fccbf8cc72598ae602fd12dec980364b/src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java#L190-L192

Please consider being more precise with the return type. The load model within SIMONA, e.g. expects to get a standard load profile (which exists to distinguish known standard profiles from individual ones).

**Comment by ckittl** [comment]
https://github.com/ie3-institute/PowerSystemDataModel/blob/74124101fccbf8cc72598ae602fd12dec980364b/src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java#L283-L286

Needs adaption too.

**Comment by sebastian-peter** [comment]
Since we now also have the ability to specify temperature dependent load profiles, this is not required anymore
