### ISSUE TITLE
Consider referencing connectedAssets of EmInput as objects instead of their uuids

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemDataModel#640]
I don't know how much effort it would take in PSDM, but I think it'd be nice to have the connected assets here directly instead of just their UUIDs. There's some discussion to be had here for sure, and this might not be possible in the short term though.

_Originally posted by @sebastian-peter in https://github.com/ie3-institute/PowerSystemDataModel/pull/591#discussion_r935397321_

**Comment by sebastian-peter** [comment]
Does not apply anymore with #957, furthermore linked `EmInput` objects within system participants does not make that much sense.
