### ISSUE TITLE
Fix `FlexOptionsResult.toString`

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/PowerSystemDataModel#693]
The wrong class name is used:

https://github.com/ie3-institute/PowerSystemDataModel/blob/91d7ff4f2b2620849688828aa7b61b972fcd0163/src/main/java/edu/ie3/datamodel/models/result/system/FlexOptionsResult.java#L96-L97

**Comment by zaino97** [comment]
@sebastian-peter can you assign this to me?

**Comment by sebastian-peter** [comment]
@zaino97 Sure, go ahead :) We have not had time yet to set up proper contributing guidelines, but if you just fork the project, mention your changes in the CHANGELOG.md and create a pull request, I'll review it
