### ISSUE TITLE
Check if MeasurementUnits should be placed in AggregatedGridInput or AggregatedRawGridInput

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#7]
Currently, measurementUnits are placed in the wrapper class for a complete grid (AggregatedGridInput) instead of the class with all raw grid elements AggregatedRawGridInput. Maybe it makes  sense to put the measurement units also in the raw grid elements class as they logically belong there?!

**Comment by ckittl** [comment]
Was duplicated by #37 and is resolved by #44, therefore closed.
