### ISSUE TITLE
Update `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/PowerSystemDataModel#737]
Similar to https://github.com/ie3-institute/simona/issues/201

**Comment by pierrepetersmeier** [comment]
@sebastian-peter 

The JavaDoc (line 19) link is no longer working. Does this refer to a link to a Java Documentation or the JavaDoc software itself?
And Are they still involved in the project (@sensarmad,@ckittl)?

**Comment by sebastian-peter** [comment]
I'd consider taking care of JavaDoc as part of [this](https://github.com/ie3-institute/PowerSystemDataModel/issues/494), so maybe just remove the mentioning here.

As to the mentioning of authors, I'd remove the list in `CONTRIBUTING.md` and link to an (updated) `AUTHORS` file. There, please also add @danielfeismann, @SimonHuette, @jo-bao, @julianhohmann and yourself to the list of main contributors and Thomas, Daniel, Johannes Bao and me to the list of lead devs. Hope that I have not forgotten anyone.
