### ISSUE TITLE
Improving ValidationUtils

### ISSUE THREAD

**Issue by staudtMarius** [ie3-institute/PowerSystemDataModel#758]
There are two main points in class ``ValidationUtils`` :

- [x] non critical validations (e.g. geometry) should no longer throw exceptions instead their validation results should be logged.
- [x] all thrown exceptions should be collected and thrown at the end of the validation process using the ``Try`` class introduced in #712 

TO
- [x] Check uniqueness of identifiers 
- [x] Implement a connectivity check, as done in SIMONA in `GridModel.validateConnectivity` as part of the container validation utils

**Comment by t-ober** [comment]
I added another item:

Currently we do not check whether ids of all the elements of a type (e.g. PvInputs) are unique. This is something we require in Simona simulations, so it makes sense to check that and at least issue a warning, maybe even throw an exception.
