### ISSUE TITLE
Replace usage of Optional<> in constructors and fields

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#8]
Currently we are using `Optional` as constructor and filed parameters in some places. While this isn't cause a problem for now (and we already discussed that this makes sense in our case), I just discovered that this prevents the classes using it from being Serializable. As we will depend on serialization in several places this might become a problem in the future. Hence, finding another solution might be unavoidable.

**Comment by mia-krause** [comment]
What about a dedicated class with builder pattern? Like OperationTime.builder().withStart("2020-01-01 00:00).withEnd("2020-12-31 23:59").build() with real dates of course.
