### ISSUE TITLE
Source cannot read SwitchInput with parallelDevices

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemDataModel#840]
This should work as it is a `ConnectorInput` which implements the attribute. Although it always has to be 1 we should maybe be able to read it when in fact it is 1.

```
uuid -> ee77cdb0-8a1d-425e-99c6-5eeec893dc01} are invalid for instance of SwitchInput. 
The following fields (without complex objects e.g. nodes, operators, ...) to be passed to a constructor of 'SwitchInput' are possible (NOT case-sensitive!):
0: [closed, id, uuid]
1: [closed, id, operatesfrom, uuid]
2: [closed, id, operatesuntil, uuid]
3: [closed, id, operatesfrom, operatesuntil, uuid]
```

**Comment by sebastian-peter** [comment]
Just looking up what `parallelDevices` does, multiple switches in parallel do not make sense, as they practically have zero impedance. 
But you're saying there's a case where still using this column with switches is more convenient than not?

**Comment by staudtMarius** [comment]
With #926 it can be read without throwing an exception. The given value of `parallelDevices` will just be ignored by the constructor. 
Maybe it is necessary to add a validation in the `ValidationUtils` to check this field?

**Comment by t-ober** [comment]
> Just looking up what `parallelDevices` does, multiple switches in parallel do not make sense, as they practically have zero impedance. But you're saying there's a case where still using this column with switches is more convenient than not?

I just thought it is weird (and highly confusing) that Switches are ConnectorInputs which neccessarily have an attribute `parallelDevices` which has to be 1 for switches, but in fact reading it with this attribute is not possible
