### ISSUE TITLE
DOD Documentation for StorageInput is not clear

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemDataModel#872]
"Maximum permissible depth of discharge. 80 % dod is equivalent to a state of charge of 20 %."

We use this value differently in SIMONA :

`private val minEnergy = eStorage * dod.toEach`

We should either adapt the documentation or change the SIMONA implementation.

**Comment by sebastian-peter** [comment]
From what I've read now, the defintion in PSDM seems correct and the implemetation in SIMONA incorrect. (Besides the point, maybe we should rename the parameter to `dodMax`, because that seems to be more descriptive).

**Comment by danielfeismann** [comment]
I also checked the defintion and agree to @sebastian-peter. Thinking about this I come to the conclusion, that in my opinion we don't need the dod at all if we agree to see the `eStorage` as the storage usable capacity. For all application cases we have so far we don't deep-discharge the battery and if one would do so this only makes sense if there are implications on the battery life time modeled which isn't so far. So I would opt to change this issue into one removing dod from documentation and code.

**Comment by sebastian-peter** [comment]
Thinking about it more, I tend to agree with @danielfeismann. `dod` is not a parameter that we're (currently) interested in. Same goes for `lifeTime` and `lifeCycle`, which we do not consider for any other asset as well. If we'd come to the conclusion in the future that we'll need this again, we could just add it back in. 

So if no-one disagrees, I'd go ahead and give green light for removing said parameters above from code and documentation.
