### ISSUE TITLE
Fix CHPTypeInput + ChpInput

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#9]
At the moment there are unused constructor parameters in the ChpTypeInput class and ChpInput class.
I'm not sure about their usage/if we need them, hence I cannot address this issue. :-(

If someone could provide more information on this I can try to fix this as well.

**Comment by mia-krause** [comment]
Versions from the previous repo have those fields, I don't know if they simply got lost in merge or were removed intentionally. Maybe @ckittl knows?

**Comment by ckittl** [comment]
@mia-krause and @johanneshiry: Is this still an issue. I don't see any unused parameters anymore...

**Comment by johanneshiry** [comment]
has been fixed
